# Generated by Django 5.2.4 on 2025-08-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hero",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID героя",
                    ),
                ),
                ("name", models.CharField(max_length=1024, verbose_name="Имя героя")),
                (
                    "intelligence",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Интеллект героя"
                    ),
                ),
                (
                    "strength",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Сила героя"
                    ),
                ),
                (
                    "speed",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Скорость героя"
                    ),
                ),
                (
                    "power",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Мощь героя"
                    ),
                ),
            ],
            options={
                "verbose_name": "Герой",
                "verbose_name_plural": "Герои",
                "ordering": ["id"],
            },
        ),
    ]
