# Generated by Django 5.2.4 on 2025-08-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="hero",
            index=models.Index(
                fields=["name", "intelligence", "strength", "speed", "power"],
                name="parameters_search_index",
            ),
        ),
    ]
